name: Charm test

on: [push]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install tox
        run: pip install tox
      - name: Lint code
        run: tox -e lint
      - name: Run unit tests
        run: tox -e test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
      - name: Configure kubectl
        run: sg microk8s -c "microk8s config > ~/.kube/config"
      - name: Run integration tests
        run: sg microk8s -c "tox -e opstest -- --model testing"

        # On failure, capture debugging resources
      - name: Get all
        run: kubectl get all -A
        if: failure()

      - name: Describe deployments
        run: kubectl describe deployments -A
        if: failure()

      - name: Describe replicasets
        run: kubectl describe replicasets -A
        if: failure()

      - name: Get juju status
        run: juju status
        if: failure()

      - name: Get application logs
        run: kubectl logs -n testing --tail 1000 -lapp.kubernetes.io/name=mlmd
        if: failure()

      - name: Get application operator logs
        run: kubectl logs -n testing --tail 1000 -ljuju-operator=mlmd
        if: failure()
